#!/bin/python3

import math
import os
import random
import re
import sys


if __name__ == '__main__':
    s = input()
    d = {}
    for c in list(set(list(s))):
        d[c] = s.count(c)
    tmp = sorted(d.items(), key=lambda x:(-x[1], x[0]))
    # print(tmp)
    for i in range(3):
        print("%s %d" % (tmp[i][0], tmp[i][1]))
